FROM node:19.8.1-alpine3.17 AS builder
ENV NODE_ENV production
WORKDIR /app
# COPY package.json .
# RUN npm install
# --production
# COPY . .
# RUN npm run build 
# FROM nginx:stable-alpine3.17-slim
# COPY --from=builder /app/build /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]
# CMD ["npm","start","--","--port","80"] 


