version: "3"

###########################################################################
# Prerequisites

#  SonarQube and Opensearch
#    sysctl -w vm.max_map_count=524288
#    sysctl -w fs.file-max=131072
#    ulimit -n 131072
#    ulimit -u 8192

# Reference: https://hub.docker.com/_/SonarQube
############################################################################

services:
  reverse-proxy:
    build: ./reverse-proxy
    depends_on:
      - flipkart-ui
    ports:
      - 80:80
      - 443:443

  flipkart-ui:
    build: ./flipkart-ui
    depends_on:
      - product-management
    volumes:
      - ./flipkart-ui:/app
    command: "tail -F anything"
    # ports:
    #   - 3000:3000

  product-management:
    build: ./product-management
    depends_on:
      - mongodb
      - s3server
      - keycloak
    ports:
      - 8088:8080
      # - 5005:5005
    environment:
      - FRONT_END_WEB_ORIGIN=https://localhost
      - ALLOWED_ORIGIN=https://localhost
      - AWS_SERVICE_ENDPOINT=http://s3server:8000
      - MONGODB_HOST=mongodb
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-your_stripe_secret_key_here}
      # - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005
    volumes:
      - "${HOME}/.m2:/root/.m2"

  postgresdb:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      KC_DB_NAME: ${KC_DB_NAME:-keycloak}
      KC_DB_USER: ${KC_DB_USER:-keycloak}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD:-keycloak}
    volumes:
      - ./postgresdb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresdb/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  mongodb:
    image: mongo:5.0.15
    # ports:
    #   - 27017:27017
    volumes:
      - ./mongodb/data/db:/data/db:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-example}

  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD:-example}
      ME_CONFIG_MONGODB_URL: ${MONGODB_CONNECTION_URL:-mongodb://root:example@mongodb:27017/}

  s3server:
    build: ./cloudserver
    volumes:
      - ./cloudserver/data:/usr/src/app/localData
      - ./cloudserver/metadata:/usr/src/app/localMetadata
    environment:
      S3BACKEND: file
      ENDPOINT: http://localhost
      REMOTE_MANAGEMENT_DISABLE: 1
      SCALITY_ACCESS_KEY_ID: ${S3_SERVER_ACCESS_KEY_ID:-accessKey1}
      SCALITY_SECRET_ACCESS_KEY: ${S3_SERVER_SECRET_ACCESS_KEY:-verySecretKey1}
    # ports:
    #   - "8000:8000"

  s3manager:
    container_name: s3manger
    hostname: s3manager
    image: mastertinner/s3manager
    ports:
      - 8001:8081
    environment:
      PORT: 8081
      ENDPOINT: ${S3_SERVER_ENDPOINT:-s3server:8000}
      ACCESS_KEY_ID: ${S3_SERVER_ACCESS_KEY_ID:-accessKey1}
      SECRET_ACCESS_KEY: ${S3_SERVER_SECRET_ACCESS_KEY:-verySecretKey1}
      USE_SSL: false
    depends_on:
      - s3server

  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - postgresdb
    environment:
      SONAR_JDBC_URL: ${SONARQUBE_JDBC_URL:-jdbc:postgresql://postgresdb:5432/sonar}
      SONAR_JDBC_USERNAME: ${SONARQUBE_USER:-sonar}
      SONAR_JDBC_PASSWORD: ${SONARQUBE_PASSWORD:-sonar}
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    ports:
      - "9000:9000"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    depends_on:
      - postgresdb
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-keycloak}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-keycloak}
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL:-jdbc:postgresql://postgresdb:5432/keycloak}
      KC_DB_USERNAME: ${KC_DB_USER:-keycloak}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD:-keycloak}
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: DEBUG
      KC_HTTP_RELATIVE_PATH: /auth
      PROXY_ADDRESS_FORWARDING: "true"
      KC_PROXY: edge
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json

  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - cluster.initial_cluster_manager_nodes=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://admin:admin@localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]'

  # logstash:
  #   build: ./logstash
  #   volumes:
  #     - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #     - ./logstash/indices/products.json:/indices/products.json
  #     - ./logstash/jar/mongodb-driver-sync-4.9.1.jar:/usr/share/logstash/logstash-core/lib/jars/mongodb-driver-sync-4.9.1.jar

  init_opensearch:
    image: curlimages/curl
    volumes:
      - ./opensearch/init_opensearch.sh:/init_opensearch.sh
    command: ["/bin/sh", "-c", "/init_opensearch.sh"]
    depends_on:
      opensearch-node1:
        condition: service_healthy

  monstache:
    image: rwynn/monstache
    working_dir: /monstache
    command: -f ./config.toml
    volumes:
      - ./monstache:/monstache/
    ports:
      - "8123:8080"
    depends_on:
      init_opensearch:
        condition: service_completed_successfully
    restart: always

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  opensearch-data1:
