spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/flipkart-clone/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/flipkart-clone

logging:
  level:
    org.springframework.security: trace